-- INSERT INTO DISK (ID, NAME, PATH) VALUES (1, 'TCADCAE01', '/SLOWFS/TCADCAE01');
-- INSERT INTO DISK (ID, NAME, PATH) VALUES (2, 'TCADCAE02', '/SLOWFS/TCADCAE02');
-- INSERT INTO DISK (ID, NAME, PATH) VALUES (3, 'TCADCAE03', '/SLOWFS/TCADCAE03');
-- INSERT INTO DISK (ID, NAME, PATH) VALUES (4, 'TCADCAE04', '/SLOWFS/TCADCAE04');
-- INSERT INTO DISK (ID, NAME, PATH) VALUES (5, 'TCADCAE06', '/SLOWFS/TCADCAE06');
-- INSERT INTO DISK (ID, NAME, PATH) VALUES (6, 'TCADCAE07', '/SLOWFS/TCADCAE07');
-- INSERT INTO DISK (ID, NAME, PATH) VALUES (7, 'TCAD_CAE_HP1', '/REMOTE/TCAD_CAE_HP1');
-- INSERT INTO DISK (ID, NAME, PATH) VALUES (8, 'TCAD_CAE_HP2', '/REMOTE/TCAD_CAE_HP2');
-- INSERT INTO DISK (ID, NAME, PATH) VALUES (9, 'TCAD_CAE_HP3', '/REMOTE/TCAD_CAE_HP3');
-- INSERT INTO DISK (ID, NAME, PATH) VALUES (10, 'TCAD_CAE_HP4', '/REMOTE/TCAD_CAE_HP4');
-- INSERT INTO DISK (ID, NAME, PATH) VALUES (11, 'TCAD_CAE_HP5', '/REMOTE/TCAD_CAE_HP5');
-- INSERT INTO DISK (ID, NAME, PATH) VALUES (12, 'TCAD_CAE_HP6', '/REMOTE/TCAD_CAE_HP6');
-- INSERT INTO DISK (ID, NAME, PATH) VALUES (13, 'TCAD_CAE_HP7', '/REMOTE/TCAD_CAE_HP7');

INSERT INTO DISK (PATH, DISK_TYPE) VALUES ('/SLOWFS/TCADCAE01', 'TierII');
INSERT INTO DISK (PATH, DISK_TYPE) VALUES ('/SLOWFS/TCADCAE02', 'TierII');
INSERT INTO DISK (PATH, DISK_TYPE) VALUES ('/SLOWFS/TCADCAE03', 'TierII');
INSERT INTO DISK (PATH, DISK_TYPE) VALUES ('/SLOWFS/TCADCAE04', 'TierII');
INSERT INTO DISK (PATH, DISK_TYPE) VALUES ('/SLOWFS/TCADCAE06', 'TierII');
INSERT INTO DISK (PATH, DISK_TYPE) VALUES ('/SLOWFS/TCADCAE07', 'TierII');
INSERT INTO DISK (PATH, DISK_TYPE) VALUES ('/REMOTE/TCAD_CAE_HP1', 'TierI');
INSERT INTO DISK (PATH, DISK_TYPE) VALUES ('/REMOTE/TCAD_CAE_HP2', 'TierI');
INSERT INTO DISK (PATH, DISK_TYPE) VALUES ('/REMOTE/TCAD_CAE_HP3', 'TierI');
INSERT INTO DISK (PATH, DISK_TYPE) VALUES ('/REMOTE/TCAD_CAE_HP4', 'TierI');
INSERT INTO DISK (PATH, DISK_TYPE) VALUES ('/REMOTE/TCAD_CAE_HP5', 'TierI');
INSERT INTO DISK (PATH, DISK_TYPE) VALUES ('/REMOTE/TCAD_CAE_HP6', 'TierI');
INSERT INTO DISK (PATH, DISK_TYPE) VALUES ('/REMOTE/TCAD_CAE_HP7', 'TierI');

INSERT INTO USER (EMAIL, FIRST_NAME, LAST_NAME, SNPS_ID)
    VALUES ('YEQING@SYNOPSYS.COM', 'YEQING', 'LU', 'YEQING')
